import { toast } from 'sonner';
import type {
  BackendUser,
  User,
  CreateUserRequest,
  UpdateUserRequest,
  UpdateProfileRequest,
  Factory,
  CreateFactoryRequest,
  UpdateFactoryRequest,
  Machine,
  CreateMachineRequest,
  UpdateMachineRequest,
  MachineStatus,
  RealtimeHistoryResponse,
  SPCHistoryResponse,
  HistoryQueryParams,
  Subscription,
  CreateSubscriptionRequest,
  HealthStatus,
  ApiError,
  AlarmHistoryResponse,
  BillingSubscription,
  BillingPlan,
  PaymentMethod,
  CheckoutSessionRequest,
  CheckoutSessionResponse,
  PortalSessionRequest,
  PortalSessionResponse,
  BillingDemoInfo,
  SpcSeriesResponse,
} from '@/types/api';
import { createLogger } from '@/utils/logger';
import { getApiBaseUrl } from '@/utils/apiBaseUrl';
import { getAccessToken } from '@/services/apiClient';

const logger = createLogger('API');
const BASE_URL = getApiBaseUrl();

interface RequestOptions extends RequestInit {
  token?: string;
  skipErrorToast?: boolean;
}

/**
 * CSRF Token Manager
 * Handles CSRF token storage and validation
 */
class CSRFTokenManager {
  private token: string | null = null;
  private readonly storageKey = 'csrf_token';

  /**
   * Get CSRF token from localStorage
   */
  getToken(): string | null {
    if (!this.token) {
      this.token = localStorage.getItem(this.storageKey);
    }
    return this.token;
  }

  /**
   * Set CSRF token in localStorage and memory
   */
  setToken(token: string | null): void {
    this.token = token;
    if (token) {
      localStorage.setItem(this.storageKey, token);
    } else {
      localStorage.removeItem(this.storageKey);
    }
  }

  /**
   * Clear CSRF token
   */
  clearToken(): void {
    this.token = null;
    localStorage.removeItem(this.storageKey);
  }

  /**
   * Generate a random CSRF token
   * Note: In production, tokens should be generated by the server
   */
  generateToken(): string {
    const array = new Uint8Array(32);
    crypto.getRandomValues(array);
    return Array.from(array, (byte) => byte.toString(16).padStart(2, '0')).join('');
  }
}

class ApiClient {
  private csrfManager = new CSRFTokenManager();

  /**
   * Normalize subscription data from backend format to frontend format
   * Handles field name mapping and timestamp conversion
   */
  private normalizeSubscription(data: any): BillingSubscription | null {
    if (!data) return null;

    return {
      subscriptionId: data.id || data.subscriptionId,
      status: data.status,
      planId: data.plan?.id || data.planId,
      currentPeriodEnd: data.currentPeriodEnd
        ? new Date(data.currentPeriodEnd * 1000).toISOString()
        : data.currentPeriodEnd,
      cancelAtPeriodEnd: data.cancelAtPeriodEnd || false,
      createdAt: data.currentPeriodStart
        ? new Date(data.currentPeriodStart * 1000).toISOString()
        : data.createdAt,
      trialEnd: data.trialEnd
        ? new Date(data.trialEnd * 1000).toISOString()
        : data.trialEnd,
    };
  }

  /**
   * Get CSRF token for state-changing operations
   * The token should be validated by the backend
   */
  getCSRFToken(): string | null {
    return this.csrfManager.getToken();
  }

  /**
   * Set CSRF token (usually received from backend)
   */
  setCSRFToken(token: string | null): void {
    this.csrfManager.setToken(token);
  }

  private async request<T>(endpoint: string, options: RequestOptions = {}): Promise<T> {
    const { skipErrorToast, ...fetchOptions } = options;

    const headers: HeadersInit = {
      'Content-Type': 'application/json',
      ...fetchOptions.headers,
    };

    const token = await getAccessToken();
    if (token) {
      (headers as Record<string, string>)['Authorization'] = `Bearer ${token}`;
    }

    // Add CSRF token for state-changing operations
    const method = (fetchOptions.method || 'GET').toUpperCase();
    if (['POST', 'PUT', 'PATCH', 'DELETE'].includes(method)) {
      const csrfToken = this.getCSRFToken();
      if (csrfToken) {
        (headers as Record<string, string>)['X-CSRF-Token'] = csrfToken;
      }
    }

    try {
      const response = await fetch(`${BASE_URL}${endpoint}`, {
        ...fetchOptions,
        headers,
      });

      if (!response.ok) {
        const errorData: ApiError = await response.json().catch(() => ({
          statusCode: response.status,
          message: response.statusText,
        }));

        // Handle specific error codes
        if (response.status === 401) {
          if (!skipErrorToast) {
            toast.error('Session expired. Please log in again.');
          }
          throw new Error(errorData.message || 'Unauthorized');
        }

        if (response.status === 403) {
          if (!skipErrorToast) {
            toast.error('You do not have permission to perform this action.');
          }
          throw new Error(errorData.message || 'Forbidden');
        }

        if (response.status === 404) {
          if (!skipErrorToast) {
            toast.error('Resource not found.');
          }
          throw new Error(errorData.message || 'Not Found');
        }

        if (response.status >= 500) {
          if (!skipErrorToast) {
            toast.error('Server error. Please try again later.');
          }
          throw new Error(errorData.message || 'Server Error');
        }

        if (!skipErrorToast) {
          toast.error(errorData.message || 'An error occurred');
        }
        throw new Error(errorData.message || `API Error: ${response.statusText}`);
      }

      // Handle empty responses
      const text = await response.text();
      if (!text) {
        return {} as T;
      }
      return JSON.parse(text);
    } catch (error) {
      if (error instanceof TypeError && error.message === 'Failed to fetch') {
        if (!skipErrorToast) {
          toast.error('Network error. Please check your connection.');
        }
        throw new Error('Network error');
      }
      throw error;
    }
  }

  // ============ Auth Endpoints ============
  async getProfile(): Promise<BackendUser> {
    return this.request<BackendUser>('/auth/profile');
  }

  async updateProfile(data: UpdateProfileRequest): Promise<BackendUser> {
    const response = await this.request<BackendUser>('/auth/profile', {
      method: 'PUT',
      body: JSON.stringify(data),
    });
    toast.success('Profile updated successfully');
    return response;
  }

  // ============ Factory Endpoints ============
  async getFactories(): Promise<Factory[]> {
    return this.request<Factory[]>('/factories');
  }

  async getFactory(id: number): Promise<Factory> {
    return this.request<Factory>(`/factories/${id}`);
  }

  async createFactory(data: CreateFactoryRequest): Promise<Factory> {
    const response = await this.request<Factory>('/factories', {
      method: 'POST',
      body: JSON.stringify(data),
    });
    toast.success('Factory created successfully');
    return response;
  }

  async updateFactory(id: number, data: UpdateFactoryRequest): Promise<Factory> {
    const response = await this.request<Factory>(`/factories/${id}`, {
      method: 'PATCH',
      body: JSON.stringify(data),
    });
    toast.success('Factory updated successfully');
    return response;
  }

  async deleteFactory(id: number): Promise<void> {
    await this.request<void>(`/factories/${id}`, {
      method: 'DELETE',
    });
    toast.success('Factory deleted successfully');
  }

  // ============ Machine Endpoints ============
  async getFactoriesAndMachines(): Promise<Factory[]> {
    return this.request<Factory[]>('/machines/factories-machines');
  }

  async getMachines(): Promise<Machine[]> {
    return this.request<Machine[]>('/machines');
  }

  async getMachine(id: number | string): Promise<Machine> {
    return this.request<Machine>(`/machines/${id}`);
  }

  async createMachine(data: CreateMachineRequest): Promise<Machine> {
    const response = await this.request<Machine>('/machines', {
      method: 'POST',
      body: JSON.stringify(data),
    });
    toast.success('Machine created successfully');
    return response;
  }

  async updateMachine(id: number, data: UpdateMachineRequest): Promise<Machine> {
    const response = await this.request<Machine>(`/machines/${id}`, {
      method: 'PATCH',
      body: JSON.stringify(data),
    });
    toast.success('Machine updated successfully');
    return response;
  }

  async deleteMachine(id: number): Promise<void> {
    await this.request<void>(`/machines/${id}`, {
      method: 'DELETE',
    });
    toast.success('Machine deleted successfully');
  }

  async getMachineStatus(id: number): Promise<MachineStatus> {
    return this.request<MachineStatus>(`/machines/${id}/status`);
  }

  // ============ Historical Data Endpoints ============
  async getRealtimeHistory(
    machineId: number | string,
    params: HistoryQueryParams = {}
  ): Promise<RealtimeHistoryResponse> {
    const queryParams = new URLSearchParams();
    if (params.limit) queryParams.set('limit', params.limit.toString());
    if (params.offset) queryParams.set('offset', params.offset.toString());
    if (params.start) queryParams.set('start', params.start);
    if (params.end) queryParams.set('end', params.end);
    if (params.aggregate) queryParams.set('aggregate', params.aggregate);

    const queryString = queryParams.toString();
    return this.request<RealtimeHistoryResponse>(
      `/machines/${machineId}/realtime-history${queryString ? `?${queryString}` : ''}`
    );
  }

  async getSPCHistory(
    machineId: number | string,
    params: HistoryQueryParams = {}
  ): Promise<SPCHistoryResponse> {
    const queryParams = new URLSearchParams();
    if (params.limit) queryParams.set('limit', params.limit.toString());
    if (params.offset) queryParams.set('offset', params.offset.toString());
    if (params.start) queryParams.set('start', params.start);
    if (params.end) queryParams.set('end', params.end);
    if (params.aggregate) queryParams.set('aggregate', params.aggregate);

    const queryString = queryParams.toString();
    const response = await this.request<any>(
      `/machines/${machineId}/spc-history${queryString ? `?${queryString}` : ''}`
    );

    // Handle both direct array and wrapped response formats
    const dataArray = Array.isArray(response) ? response : (response?.data || []);

    return {
      data: dataArray,
      pagination: response?.pagination || {
        total: dataArray.length,
        limit: params.limit || 50,
        offset: params.offset || 0
      },
      metadata: response?.metadata || {
        deviceId: String(machineId),
        timeRange: `${params.start || ''} - ${params.end || ''}`,
        aggregate: params.aggregate || 'raw'
      }
    };
  }

  async getSPCLimits(
    machineId: number | string,
    fields: string,
    lookback: string = '24h',
    sigma: number = 3
  ): Promise<{
    limits: Record<string, {
      mean: number
      stdDev: number
      ucl: number
      lcl: number
      n: number
      calculatedAt: string
      expiresAt: string
      isCached: boolean
    }>
    metadata: {
      deviceId: string
      calculationTime: string
      cacheKey: string
    }
  }> {
    const queryParams = new URLSearchParams()
    queryParams.set('fields', fields)
    queryParams.set('lookback', lookback)
    queryParams.set('sigma', sigma.toString())

    return this.request(
      `/machines/${machineId}/spc/limits?${queryParams.toString()}`
    )
  }

  async getSPCSeries(
    machineId: number | string,
    field: string,
    window: string = 'last_1h',
    limit: number = 100,
    downsample: string = 'none',
    includeStats: boolean = true,
    includeLimits: boolean = true
  ): Promise<SpcSeriesResponse> {
    const queryParams = new URLSearchParams()
    queryParams.set('machineId', String(machineId))
    queryParams.set('field', field)
    queryParams.set('window', window)
    queryParams.set('limit', String(limit))
    queryParams.set('downsample', downsample)
    queryParams.set('includeStats', String(includeStats))
    queryParams.set('includeLimits', String(includeLimits))

    const queryString = queryParams.toString()
    return this.request<SpcSeriesResponse>(
      `/api/spc/series${queryString ? `?${queryString}` : ''}`
    )
  }

  // ============ User Endpoints (Admin) ============
  async getUsers(): Promise<User[]> {
    return this.request<User[]>('/user');
  }

  async getUser(email: string): Promise<User> {
    return this.request<User>(`/user/${email}`);
  }

  async createUser(data: CreateUserRequest): Promise<User> {
    const response = await this.request<User>('/user', {
      method: 'POST',
      body: JSON.stringify(data),
    });
    toast.success('User created successfully');
    return response;
  }

  async updateUser(email: string, data: UpdateUserRequest): Promise<User> {
    const response = await this.request<User>(`/user/${email}`, {
      method: 'PATCH',
      body: JSON.stringify(data),
    });
    toast.success('User updated successfully');
    return response;
  }

  async deleteUser(email: string): Promise<void> {
    await this.request<void>(`/user/${email}`, {
      method: 'DELETE',
    });
    toast.success('User deleted successfully');
  }

  // ============ Alarm Endpoints ============
  async getMachineAlarms(
    machineId: number | string,
    timeRange: string = '-1h'
  ): Promise<AlarmHistoryResponse> {
    const queryParams = new URLSearchParams();
    if (timeRange) queryParams.set('timeRange', timeRange);

    const queryString = queryParams.toString();
    return this.request<AlarmHistoryResponse>(
      `/machines/${machineId}/alarms${queryString ? `?${queryString}` : ''}`
    );
  }

  // ============ Subscription Endpoints ============
  async getSubscriptions(): Promise<Subscription[]> {
    return this.request<Subscription[]>('/subscriptions');
  }

  async createSubscription(data: CreateSubscriptionRequest): Promise<Subscription> {
    const response = await this.request<Subscription>('/subscriptions', {
      method: 'POST',
      body: JSON.stringify(data),
    });
    toast.success('Subscription created successfully');
    return response;
  }

  async deleteSubscription(id: number): Promise<void> {
    await this.request<void>(`/subscriptions/${id}`, {
      method: 'DELETE',
    });
    toast.success('Subscription removed successfully');
  }

  // ============ Billing/Subscription Endpoints ============

  async getCurrentSubscription(): Promise<BillingSubscription | BillingDemoInfo | null> {
    const response = await this.request<{ subscription: BillingSubscription | BillingDemoInfo | null }>('/api/subscription/current');

    if (response.subscription === null) {
      return null;
    }

    if ('isDemo' in response.subscription) {
      return response.subscription;
    }

    return this.normalizeSubscription(response.subscription);
  }

  async getBillingPlans(): Promise<BillingPlan[]> {
    const response = await this.request<{ plans: BillingPlan[] }>('/api/subscription/plans');
    return response.plans.map(plan => ({
      ...plan,
      planId: plan.planId || plan.id || '',
    }));
  }

  async getPaymentMethods(): Promise<PaymentMethod[]> {
    const response = await this.request<{ status: string; data: { payment_methods: PaymentMethod[] } }>('/api/subscription/payment-methods');
    return response.data?.payment_methods || [];
  }

  async createCheckoutSession(data: CheckoutSessionRequest & {
    idempotencyKey?: string;
    metadata?: Record<string, string>;
  }): Promise<CheckoutSessionResponse> {
    const body: Record<string, any> = {
      lookupKey: data.lookupKey,
      successUrl: data.successUrl,
      cancelUrl: data.cancelUrl,
    };

    // Add idempotency key if provided (for Stripe best practices)
    if (data.idempotencyKey) {
      body.idempotencyKey = data.idempotencyKey;
    }

    // Add metadata if provided (for debugging and audit)
    if (data.metadata) {
      body.metadata = data.metadata;
    }

    const response = await this.request<{ status: string; data: CheckoutSessionResponse }>('/api/subscription/create-checkout-session', {
      method: 'POST',
      body: JSON.stringify(body),
    });
    return response.data;
  }

  async createPortalSession(data: PortalSessionRequest): Promise<PortalSessionResponse> {
    const response = await this.request<{ status: string; data: PortalSessionResponse }>('/api/subscription/create-portal-session', {
      method: 'POST',
      body: JSON.stringify(data),
    });
    return response.data;
  }

  async cancelBillingSubscription(subscriptionId: string): Promise<void> {
    await this.request<void>(`/api/subscription/${subscriptionId}`, {
      method: 'DELETE',
    });
    toast.success('Subscription will be canceled at period end');
  }

  // ============ Additional Payment Endpoints ============
  // Note: These endpoints may not be implemented in the backend yet
  // They are included for future enhancement

  async getInvoices(): Promise<import('@/types/api').Invoice[]> {
    try {
      return await this.request<import('@/types/api').Invoice[]>('/api/subscription/invoices');
    } catch (error) {
      logger.warn('getInvoices endpoint not available yet:', error);
      return [];
    }
  }

  async getUsage(): Promise<import('@/types/api').UsageMetrics | null> {
    try {
      return await this.request<import('@/types/api').UsageMetrics>('/api/subscription/usage');
    } catch (error) {
      logger.warn('getUsage endpoint not available yet:', error);
      return null;
    }
  }

  async applyCoupon(code: string): Promise<{ discount?: any }> {
    try {
      return await this.request<{ discount?: any }>('/api/subscription/coupon', {
        method: 'POST',
        body: JSON.stringify({ code }),
      });
    } catch (error) {
      logger.warn('applyCoupon endpoint not available yet:', error);
      return {};
    }
  }

  // ============ Health Endpoints ============
  async getHealth(): Promise<HealthStatus> {
    return this.request<HealthStatus>('/health', { skipErrorToast: true });
  }
}

export const api = new ApiClient();
